title: Data Movement-Centric Computing
description: Research notes on data movement in modern AI deployment.
theme: minima
permalink: /:year/:month/:day/:title/
timezone: America/Vancouver
future: true

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
